export const categoriesMetadataConfigs = {
  sports: {
    title: "Latest Football, Badminton, Tennis & Motorsports News | FMT Sports",
    description:
      "Get the latest sports news and updates on football, badminton, tennis, and motorsports. Enjoy comprehensive coverage, expert analyses, scores, and in-depth sports commentary on FMT Sports",
    keywords: [
      "latest sports news",
      "football news Malaysia",
      "badminton highlights",
      "tennis updates",
      "motorsports news",
      "sports analysis",
      "international sports updates",
      "world cup news",
      "Asian games badminton",
      "Formula 1 updates",
      "Premier League news",
      "Malaysia sports achievements",
      "global tennis events",
      "motorsports highlights",
      "sports commentary",
      "athlete interviews",
      "sports injury updates",
      "fitness and training",
      "women in sports",
      "e-sports news",
      "sports tech advancements",
      "football match previews",
      "badminton match results",
      "tennis match scores",
      "motorsports race analysis",
    ],
    category:
      "sports, landing, sports homepage, football, badminton, tennis, motorsports, sports news",
    alternateLocale: [
      "en_US",
      "en_GB",
      "en_AU",
      "en_CA",
      "en_NZ",
      "en_IE",
      "en_IN",
      "en_SG",
      "en_ZA",
      "en_PH",
      "en_HK",
      "en_PK",
    ],
    pathName: "/home-sports",
  },
  business: {
    title: "Malaysia Business News, Economy & Finance Updates | FMT Business",
    description:
      "Stay updated with the latest Malaysia business news, economy updates, and financial insights. Get comprehensive coverage of market trends, industry analysis, and economic developments.",
    keywords: [
      "malaysia business news",
      "economy updates",
      "financial news",
      // ... rest of business keywords
    ],
    category: "business, economy, finance, market, industry",
    alternateLocale: [
      "en_US",
      "en_GB",
      "en_AU",
      "en_CA",
      "en_NZ",
      "en_IE",
      "en_IN",
      "en_SG",
      "en_ZA",
      "en_PH",
      "en_HK",
      "en_PK",
    ],
    pathName: "/home-business",
  },
};
