export const categoriesMetadataConfigs = {
  news: {
    title:
      "Latest News from East & West Malaysia, Sabah & Sarawak | Free Malaysia Today",
    description:
      "Discover the latest breaking news, in-depth stories, and updates from East & West Malaysia, including Sabah and Sarawak, on FMT.",
    keywords: [
      "Malaysia latest news",
      "East Malaysia news",
      "West Malaysia headlines",
      "Sabah news updates",
      "Sarawak current events",
      "Borneo news today",
      "Malaysian politics",
      "Local news Malaysia",
      "Malaysia economic news",
      "Cultural news in Malaysia",
      "Environmental news Malaysia",
      "Malaysia sports news",
      "Breaking news Malaysia",
      "Current affairs Malaysia",
      "Malaysian government updates",
      "Business news Malaysia",
      "Social issues Malaysia",
      "Education news Malaysia",
      "Health news Malaysia",
      "Technology news Malaysia",
      "Crime news Malaysia",
      "Entertainment news Malaysia",
      "Weather updates Malaysia",
      "Transportation news Malaysia",
    ],
    category:
      "News, Malaysia, East Malaysia, West Malaysia, Sabah, Sarawak, Borneo, Politics, Local News, landing",
    pathName: "/news",
    imageAlt: "East & West Malaysia, Sabah & Sarawak | Free Malaysia Today",
  },

  berita: {
    title: "Berita Terkini Malaysia & Dunia | FMT Bahasa Melayu",
    description:
      "Dapatkan berita terkini, politik, tempatan, dan internasional dari Malaysia dengan sumber yang dipercayai di Free Malaysia Today (FMT) dalam Bahasa Melayu.",
    keywords: [
      "berita terkini Malaysia",
      "berita politik terkini",
      "berita Malaysia hari ini",
      "dunia berita BM terbaru",
      "FMT Bahasa Melayu",
      "berita tempatan terbaru",
      "sumber berita terpercaya",
      "berita semasa Malaysia",
      "berita antarabangsa BM",
      "Free Malaysia Today BM",
      "berita hari ini",
      "info terkini MY",
      "berita penting hari ini",
      "berita dunia terkini BM",
      "berita panas Malaysia",
      "berita utama Malaysia",
      "info Malaysia terkini",
      "abg berita politik",
      "berita viral MY",
      "berita ekonomi Malaysia",
      "berita semasa",
      "berita terhangat",
      "berita Malaysia",
      "berita politik Malaysia",
      "berita terkini dunia",
    ],
    category: "Berita, terkini, Malaysia, dunia, politik, berita utama",
    pathName: "/berita",
    imageAlt: "Free Malaysia Today (FMT) Bahasa Melayu",
  },

  sports: {
    title: "Latest Football, Badminton, Tennis & Motorsports News | FMT Sports",
    description:
      "Get the latest sports news and updates on football, badminton, tennis, and motorsports. Enjoy comprehensive coverage, expert analyses, scores, and in-depth sports commentary on FMT Sports",
    keywords: [
      "latest sports news",
      "football news Malaysia",
      "badminton highlights",
      "tennis updates",
      "motorsports news",
      "sports analysis",
      "international sports updates",
      "world cup news",
      "Asian games badminton",
      "Formula 1 updates",
      "Premier League news",
      "Malaysia sports achievements",
      "global tennis events",
      "motorsports highlights",
      "sports commentary",
      "athlete interviews",
      "sports injury updates",
      "fitness and training",
      "women in sports",
      "e-sports news",
      "sports tech advancements",
      "football match previews",
      "badminton match results",
      "tennis match scores",
      "motorsports race analysis",
    ],
    category:
      "sports, landing, sports homepage, football, badminton, tennis, motorsports, sports news",
    imageAlt:
      "Latest Football, Badminton, Tennis & Motorsports News | FMT Sports",
    pathName: "/sports",
  },
  business: {
    title: "Latest Local & World Business News | FMT Business Insights",
    description:
      "Stay updated with the latest local and global business and finance news, market analysis, stock updates, and economic headlines on Free Malaysia Today (FMT).",
    keywords: [
      "Malaysia business news",
      "global business updates",
      "stock market news",
      "finance news Malaysia",
      "latest economic news",
      "business headlines FMT",
      "local market analysis",
      "international finance updates",
      "economic headlines today",
      "business trends",
      "financial market insights",
      "Malaysia stock updates",
      "world economic analysis",
      "business investment news",
      "FMT business reports",
      "latest market trends",
      "financial news updates",
      "Malaysia economy news",
      "global finance news",
      "business market conditions",
      "corporate news Malaysia",
      "banking sector updates",
      "real estate market news",
      "cryptocurrency updates",
      "SME business news",
    ],
    category: "business, landing, business homepage",
    imageAlt: "FMT Business News",
    pathName: "/business",
  },

  opinion: {
    title:
      "Global Insights and Malaysian Perspectives | Opinion - Free Malaysia Today",
    description:
      "Dive into compelling opinions and thought-provoking analyses on FMT. Explore expert columns, editorials, and reader letters on pressing topics including politics, policy, societal trends, and international affairs.",
    keywords: [
      "Malaysian opinion",
      "global insights",
      "political analysis",
      "societal trends",
      "expert editorials",
      "news columns",
      "reader letters",
      "international affairs",
      "policy discussions",
      "Malaysian perspectives",
      "world news opinion",
      "cultural commentary",
      "economic forecasts",
      "environmental advocacy",
      "technology debates",
      "healthcare reform opinions",
      "educational policies",
      "human rights discussions",
      "opinion pieces",
      "global politics commentary",
      "Asian news perspectives",
      "democracy and governance",
      "opinions on global crises",
      "civic engagement",
      "social justice opinions",
    ],
    imageAlt: "Global Insights and Malaysian Perspectives | FMT Opinions",
    category:
      "opinion, landing, opinion homepage, columns, editorials, letters",
    pathName: "/opinion",
  },

  lifestyle: {
    title:
      "Latest Lifestyle Trends, Health Tips & Tech Innovations | FMT Lifestyle",
    description:
      "Discover the latest in lifestyle trends, health and wellness tips, culinary delights, tech innovations, travel destinations, and financial advice with FMT Lifestyle.",
    keywords: [
      "lifestyle trends",
      "health and wellness tips",
      "culinary delights",
      "tech innovations",
      "travel destinations",
      "financial advice",
      "entertainment news",
      "automotive reviews",
      "pet care tips",
      "money-saving strategies",
      "world cuisine",
      "fitness and exercise",
      "eco-friendly living",
      "smart gadgets",
      "cultural experiences",
      "luxury lifestyle",
      "home decor ideas",
      "beauty and fashion",
      "DIY projects",
      "personal development",
      "sustainable travel",
      "nutritional tips",
      "latest gadgets",
      "outdoor adventure",
      "stories",
      "food trends",
      "family health",
      "financial tips",
      "travel guides",
      "pet advice",
      "tech trends",
    ],
    category: "lifestyle, landing, lifestyle homepage, health, tech, food",
    pathName: "/lifestyle",
    imageAlt: "Lifestyle | Free Malaysia Today",
  },
};
