env: standard
runtime: nodejs20
service: default

# Instance configuration
instance_class: F1

# Basic handler (let Next.js handle routing)
handlers:
  - url: /.*
    secure: always
    script: auto

# Environment variables
env_variables:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"

  # Public variables
  NEXT_PUBLIC_COMSCORE_ID: ${NEXT_PUBLIC_COMSCORE_ID}
  NEXT_PUBLIC_LOTAME_CLIENT_ID: ${NEXT_PUBLIC_LOTAME_CLIENT_ID}
  NEXT_PUBLIC_CB_UID: ${NEXT_PUBLIC_CB_UID}
  NEXT_PUBLIC_CHARTBEAT_API_KEY: ${NEXT_PUBLIC_CHARTBEAT_API_KEY}
  NEXT_PUBLIC_CHARTBEAT_HOST: ${NEXT_PUBLIC_CHARTBEAT_HOST}
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
  NEXT_PUBLIC_CDN_URL: ${NEXT_PUBLIC_CDN_URL}
  NEXT_PUBLIC_GCS_BUCKET: ${NEXT_PUBLIC_GCS_BUCKET}
  NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL}
  NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
  NEXT_PUBLIC_CRYPTO_IV: ${NEXT_PUBLIC_CRYPTO_IV}
  NEXT_PUBLIC_CRYPTO_KEY: ${NEXT_PUBLIC_CRYPTO_KEY}
  NEXT_PUBLIC_WP_REFRESH_TOKEN: ${NEXT_PUBLIC_WP_REFRESH_TOKEN}
  NEXT_PUBLIC_WORDPRESS_SECRET: ${NEXT_PUBLIC_WORDPRESS_SECRET}

  # Runtime variables
  WORDPRESS_API_URL: ${WORDPRESS_API_URL}
  DATABASE_URL: ${DATABASE_URL}
  NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  REVALIDATE_SECRET_KEY: ${REVALIDATE_SECRET_KEY}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  REVALIDATION_TOKEN: ${REVALIDATION_TOKEN}
  SYNC_KEY: ${SYNC_KEY}
  CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
  CLOUDFLARE_ZONE_ID: ${CLOUDFLARE_ZONE_ID}
  CHARTBEAT_API_KEY: ${CHARTBEAT_API_KEY}
  CHARTBEAT_HOST: ${CHARTBEAT_HOST}
  YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY}
  CONTACT_US_RECIPIENT: ${CONTACT_US_RECIPIENT}

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 2
  max_instances: 10
  max_concurrent_requests: 80
  target_concurrent_requests: 40
  min_pending_latency: 30ms
  max_pending_latency: 200ms

# Network settings
network:
  session_affinity: true

# VPC configuration (if needed)
vpc_access_connector:
  name: projects/mp-fmt-v2-stg/locations/asia-southeast1/connectors/fmt-connector

# Readiness and liveness checks
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Security settings
inbound_services:
  - warmup
