steps:
  # Step 1: Install dependencies and generate Prisma client
  - name: "node:22.16-bullseye-slim"
    id: "Generate Prisma"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "📦 Installing dependencies..."
        npm ci --legacy-peer-deps --ignore-optional

        echo "🔧 Generating Prisma client..."
        npx prisma generate

        echo "✅ Dependencies installed and Prisma client generated"

  # Step 2: Build container image with Docker layer caching
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Container"
    args:
      - "build"
      - "--progress=plain"
      - "--cache-from=asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"
      - "--target=runner"
      - "--build-arg"
      - "NODE_ENV=production"
      - "--build-arg"
      - "DATABASE_URL=${_DATABASE_URL}"
      - "--build-arg"
      - "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}"
      - "--build-arg"
      - "REVALIDATE_SECRET_KEY=${_REVALIDATE_SECRET_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_DOMAIN=${_NEXT_PUBLIC_DOMAIN}"
      - "--build-arg"
      - "CLOUDFLARE_API_TOKEN=${_CLOUDFLARE_API_TOKEN}"
      - "--build-arg"
      - "CLOUDFLARE_ZONE_ID=${_CLOUDFLARE_ZONE_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_COMSCORE_ID=${_NEXT_PUBLIC_COMSCORE_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_LOTAME_CLIENT_ID=${_NEXT_PUBLIC_LOTAME_CLIENT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_CB_UID=${_NEXT_PUBLIC_CB_UID}"
      - "--build-arg"
      - "NEXT_PUBLIC_CHARTBEAT_API_KEY=${_NEXT_PUBLIC_CHARTBEAT_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_CHARTBEAT_HOST=${_NEXT_PUBLIC_CHARTBEAT_HOST}"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
      - "--build-arg"
      - "YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}"
      - "--build-arg"
      - "WORDPRESS_API_URL=${_WORDPRESS_API_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CMS_URL=${_NEXT_PUBLIC_CMS_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CDN_URL=${_NEXT_PUBLIC_CDN_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_GCS_BUCKET=${_NEXT_PUBLIC_GCS_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_WORDPRESS_SECRET=${_NEXT_PUBLIC_WORDPRESS_SECRET}"
      - "--build-arg"
      - "NEXT_PUBLIC_WP_REFRESH_TOKEN=${_NEXT_PUBLIC_WP_REFRESH_TOKEN}"
      - "--build-arg"
      - "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}"
      - "--build-arg"
      - "REVALIDATION_TOKEN=${_REVALIDATION_TOKEN}"
      - "--build-arg"
      - "SYNC_KEY=${_SYNC_KEY}"
      - "--build-arg"
      - "CHARTBEAT_API_KEY=${_CHARTBEAT_API_KEY}"
      - "--build-arg"
      - "CHARTBEAT_HOST=${_CHARTBEAT_HOST}"
      - "--build-arg"
      - "NEXT_PUBLIC_CRYPTO_IV=${_NEXT_PUBLIC_CRYPTO_IV}"
      - "--build-arg"
      - "NEXT_PUBLIC_CRYPTO_KEY=${_NEXT_PUBLIC_CRYPTO_KEY}"
      - "--build-arg"
      - "CONTACT_US_RECIPIENT=${_CONTACT_US_RECIPIENT}"
      - "--build-arg"
      - "SENDGRID_API_KEY=${_SENDGRID_API_KEY}"
      - "--build-arg"
      - "NEXTAUTH_URL=${_NEXTAUTH_URL}"
      - "--build-arg"
      - "ADMIN_API_KEY=${_ADMIN_API_KEY}"

      - "-t"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"
      - "."

  # Step 3: Push versioned container image
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Versioned Image"
    args:
      - "push"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"

  # Step 4: Push latest tag for cache
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Latest Tag"
    args:
      - "push"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"

  # Step 5: Blue/Green Deployment to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Blue/Green"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        echo "🔍 Checking current deployment status..."
        activeEnv=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.traffic[].tags)' 2>/dev/null || echo "")

        if [[ -z "$activeEnv" ]]; then
          nextEnv="green"
        elif [[ "$activeEnv" == *"green"* ]]; then
          nextEnv="blue"
        else
          nextEnv="green"
        fi

        echo "🚀 Active: ${activeEnv:-none}, Deploying to: $nextEnv"

        echo "📦 Deploying new version to $nextEnv..."
        gcloud run deploy ${_SERVICE_NAME} \
          --image=asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA \
          --no-traffic \
          --tag=$nextEnv \
          --region=${_REGION} \
          --port=3000 \
          --memory=2Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=10 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production" \
          --set-env-vars="NEXT_TELEMETRY_DISABLED=1" \
          --set-env-vars="NODE_OPTIONS=${_NODE_OPTIONS}" \
          --set-env-vars="DATABASE_URL=${_DATABASE_URL}" \
          --set-env-vars="NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}" \
          --set-env-vars="REVALIDATE_SECRET_KEY=${_REVALIDATE_SECRET_KEY}" \
          --set-env-vars="REVALIDATE_SECRET=${_REVALIDATE_SECRET}" \
          --set-env-vars="CRON_SECRET_KEY=${_CRON_SECRET_KEY}" \
          --set-env-vars="WORDPRESS_API_URL=${_WORDPRESS_API_URL}" \
          --set-env-vars="GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}" \
          --set-env-vars="GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}" \
          --set-env-vars="REVALIDATION_TOKEN=${_REVALIDATION_TOKEN}" \
          --set-env-vars="SYNC_KEY=${_SYNC_KEY}" \
          --set-env-vars="CLOUDFLARE_API_TOKEN=${_CLOUDFLARE_API_TOKEN}" \
          --set-env-vars="CLOUDFLARE_ZONE_ID=${_CLOUDFLARE_ZONE_ID}" \
          --set-env-vars="CHARTBEAT_API_KEY=${_CHARTBEAT_API_KEY}" \
          --set-env-vars="CHARTBEAT_HOST=${_CHARTBEAT_HOST}" \
          --set-env-vars="YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}" \
          --set-env-vars="YOUTUBE_CHANNEL_ID=${_YOUTUBE_CHANNEL_ID}" \
          --set-env-vars="WEBSUB_SECRET=${_WEBSUB_SECRET}" \
          --set-env-vars="YOUTUBE_WEBHOOK_URL=${_YOUTUBE_WEBHOOK_URL}" \
          --set-env-vars="SENDGRID_API_KEY=${_SENDGRID_API_KEY}" \
          --set-env-vars="CONTACT_US_RECIPIENT=${_CONTACT_US_RECIPIENT}" \
          --set-env-vars="ADMIN_API_KEY=${_ADMIN_API_KEY}" \
          --set-env-vars="DEFAULT_PLAYLIST_ID=${_DEFAULT_PLAYLIST_ID}" \
          --set-env-vars="NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}" \
          --set-env-vars="NEXT_PUBLIC_DOMAIN=${_NEXT_PUBLIC_DOMAIN}" \
          --set-env-vars="NEXT_PUBLIC_CDN_URL=${_NEXT_PUBLIC_CDN_URL}" \
          --set-env-vars="NEXT_PUBLIC_GCS_BUCKET=${_NEXT_PUBLIC_GCS_BUCKET}" \
          --set-env-vars="NEXT_PUBLIC_CMS_URL=${_NEXT_PUBLIC_CMS_URL}" \
          --set-env-vars="NEXT_PUBLIC_COMSCORE_ID=${_NEXT_PUBLIC_COMSCORE_ID}" \
          --set-env-vars="NEXT_PUBLIC_LOTAME_CLIENT_ID=${_NEXT_PUBLIC_LOTAME_CLIENT_ID}" \
          --set-env-vars="NEXT_PUBLIC_CB_UID=${_NEXT_PUBLIC_CB_UID}" \
          --set-env-vars="NEXT_PUBLIC_CHARTBEAT_API_KEY=${_NEXT_PUBLIC_CHARTBEAT_API_KEY}" \
          --set-env-vars="NEXT_PUBLIC_CHARTBEAT_HOST=${_NEXT_PUBLIC_CHARTBEAT_HOST}" \
          --set-env-vars="NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}" \
          --set-env-vars="NEXT_PUBLIC_WORDPRESS_SECRET=${_NEXT_PUBLIC_WORDPRESS_SECRET}" \
          --set-env-vars="NEXT_PUBLIC_WP_REFRESH_TOKEN=${_NEXT_PUBLIC_WP_REFRESH_TOKEN}" \
          --set-env-vars="NEXT_PUBLIC_CRYPTO_IV=${_NEXT_PUBLIC_CRYPTO_IV}" \
          --set-env-vars="NEXT_PUBLIC_CRYPTO_KEY=${_NEXT_PUBLIC_CRYPTO_KEY}" \
          --set-env-vars="NEXTAUTH_URL=${_NEXTAUTH_URL}" \
          --timeout=300 \
          --service-account=${_SERVICE_ACCOUNT} \
          --quiet

        echo "🔍 Waiting for deployment to be ready..."
        sleep 30

        echo "🔄 Switching traffic to $nextEnv..."
        gcloud run services update-traffic ${_SERVICE_NAME} \
          --to-tags=$nextEnv=100 \
          --region=${_REGION} \
          --quiet

# Substitution variables (supplied by your trigger/Cloud Build)
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: fmt-v4

  _ADMIN_API_KEY: ${_ADMIN_API_KEY}
  _CHARTBEAT_API_KEY: ${_CHARTBEAT_API_KEY}
  _CHARTBEAT_HOST: ${_CHARTBEAT_HOST}
  _CLOUDFLARE_API_TOKEN: ${_CLOUDFLARE_API_TOKEN}
  _CLOUDFLARE_ZONE_ID: ${_CLOUDFLARE_ZONE_ID}
  _CONTACT_US_RECIPIENT: ${_CONTACT_US_RECIPIENT}
  _CRON_SECRET_KEY: ${_CRON_SECRET_KEY}
  _DATABASE_URL: ${_DATABASE_URL}
  _GOOGLE_CLIENT_ID: ${_GOOGLE_CLIENT_ID}
  _GOOGLE_CLIENT_SECRET: ${_GOOGLE_CLIENT_SECRET}
  _NEXT_PUBLIC_APP_URL: ${_NEXT_PUBLIC_APP_URL}
  _NEXT_PUBLIC_CB_UID: ${_NEXT_PUBLIC_CB_UID}
  _NEXT_PUBLIC_CDN_URL: ${_NEXT_PUBLIC_CDN_URL}
  _NEXT_PUBLIC_CHARTBEAT_API_KEY: ${_NEXT_PUBLIC_CHARTBEAT_API_KEY}
  _NEXT_PUBLIC_CHARTBEAT_HOST: ${_NEXT_PUBLIC_CHARTBEAT_HOST}
  _NEXT_PUBLIC_CMS_URL: ${_NEXT_PUBLIC_CMS_URL}
  _NEXT_PUBLIC_COMSCORE_ID: ${_NEXT_PUBLIC_COMSCORE_ID}
  _NEXT_PUBLIC_CRYPTO_IV: ${_NEXT_PUBLIC_CRYPTO_IV}
  _NEXT_PUBLIC_CRYPTO_KEY: ${_NEXT_PUBLIC_CRYPTO_KEY}
  _NEXT_PUBLIC_DOMAIN: ${_NEXT_PUBLIC_DOMAIN}
  _NEXT_PUBLIC_GCS_BUCKET: ${_NEXT_PUBLIC_GCS_BUCKET}
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}
  _NEXT_PUBLIC_LOTAME_CLIENT_ID: ${_NEXT_PUBLIC_LOTAME_CLIENT_ID}
  _NEXT_PUBLIC_WORDPRESS_SECRET: ${_NEXT_PUBLIC_WORDPRESS_SECRET}
  _NEXT_PUBLIC_WP_REFRESH_TOKEN: ${_NEXT_PUBLIC_WP_REFRESH_TOKEN}
  _NEXTAUTH_SECRET: ${_NEXTAUTH_SECRET}
  _NODE_OPTIONS: ${_NODE_OPTIONS}
  _REVALIDATE_SECRET: ${_REVALIDATE_SECRET}
  _REVALIDATE_SECRET_KEY: ${_REVALIDATE_SECRET_KEY}
  _REVALIDATION_TOKEN: ${_REVALIDATION_TOKEN}
  _SENDGRID_API_KEY: ${_SENDGRID_API_KEY}
  _SYNC_KEY: ${_SYNC_KEY}
  _WEBSUB_SECRET: ${_WEBSUB_SECRET}
  _WORDPRESS_API_URL: ${_WORDPRESS_API_URL}
  _YOUTUBE_API_KEY: ${_YOUTUBE_API_KEY}
  _YOUTUBE_CHANNEL_ID: ${_YOUTUBE_CHANNEL_ID}
  _YOUTUBE_WEBHOOK_URL: ${_YOUTUBE_WEBHOOK_URL}
  _DEFAULT_PLAYLIST_ID: ${_DEFAULT_PLAYLIST_ID}

options:
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
