steps:
  # Step 1: Install dependencies and generate Prisma client
  - name: "node:22.16-bullseye-slim"
    id: "Generate Prisma"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "📦 Installing dependencies..."
        npm ci --legacy-peer-deps --ignore-optional

        echo "🔧 Generating Prisma client..."
        npx prisma generate

        echo "✅ Dependencies installed and Prisma client generated"

  # Step 2: Build container image with Docker layer caching
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Container"
    args:
      - "build"
      - "--progress=plain"
      # Use cached layers from previous builds
      - "--cache-from=asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"
      - "--target=runner"
      # Pass all build arguments
      - "--build-arg"
      - "NODE_ENV=production"
      - "--build-arg"
      - "DATABASE_URL=${_DATABASE_URL}"
      - "--build-arg"
      - "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}"
      - "--build-arg"
      - "REVALIDATE_SECRET_KEY=${_REVALIDATE_SECRET_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_DOMAIN=${_NEXT_PUBLIC_DOMAIN}"
      - "--build-arg"
      - "CLOUDFLARE_API_TOKEN=${_CLOUDFLARE_API_TOKEN}"
      - "--build-arg"
      - "CLOUDFLARE_ZONE_ID=${_CLOUDFLARE_ZONE_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_COMSCORE_ID=${_NEXT_PUBLIC_COMSCORE_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_LOTAME_CLIENT_ID=${_NEXT_PUBLIC_LOTAME_CLIENT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_CB_UID=${_NEXT_PUBLIC_CB_UID}"
      - "--build-arg"
      - "NEXT_PUBLIC_CHARTBEAT_API_KEY=${_NEXT_PUBLIC_CHARTBEAT_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_CHARTBEAT_HOST=${_NEXT_PUBLIC_CHARTBEAT_HOST}"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
      - "--build-arg"
      - "YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}"
      - "--build-arg"
      - "WORDPRESS_API_URL=${_WORDPRESS_API_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CMS_URL=${_NEXT_PUBLIC_CMS_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CDN_URL=${_NEXT_PUBLIC_CDN_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_GCS_BUCKET=${_NEXT_PUBLIC_GCS_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_WORDPRESS_SECRET=${_NEXT_PUBLIC_WORDPRESS_SECRET}"
      - "--build-arg"
      - "NEXT_PUBLIC_WP_REFRESH_TOKEN=${_NEXT_PUBLIC_WP_REFRESH_TOKEN}"
      - "--build-arg"
      - "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}"
      - "--build-arg"
      - "REVALIDATION_TOKEN=${_REVALIDATION_TOKEN}"
      - "--build-arg"
      - "SYNC_KEY=${_SYNC_KEY}"
      - "--build-arg"
      - "CHARTBEAT_API_KEY=${_CHARTBEAT_API_KEY}"
      - "--build-arg"
      - "CHARTBEAT_HOST=${_CHARTBEAT_HOST}"
      - "--build-arg"
      - "NEXT_PUBLIC_CRYPTO_IV=${_NEXT_PUBLIC_CRYPTO_IV}"
      - "--build-arg"
      - "NEXT_PUBLIC_CRYPTO_KEY=${_NEXT_PUBLIC_CRYPTO_KEY}"
      - "--build-arg"
      - "CONTACT_US_RECIPIENT=${_CONTACT_US_RECIPIENT}"
      - "--build-arg"
      - "SENDGRID_API_KEY=${_SENDGRID_API_KEY}"
      # Tag with commit SHA and latest
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"
      - "."

  # Step 3: Push versioned container image
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Versioned Image"
    args:
      - "push"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"

  # Step 4: Push latest tag for cache
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Latest Tag"
    args:
      - "push"
      - "asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest"

  # Step 5: Blue/Green Deployment to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Blue/Green"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Determine current active environment
        echo "🔍 Checking current deployment status..."
        activeEnv=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.traffic[].tags)' 2>/dev/null || echo "")

        # Default to blue if no active environment found
        if [[ -z "$activeEnv" ]]; then
          activeEnv="blue"
          nextEnv="green"
        elif [[ "$activeEnv" == *"green"* ]]; then
          nextEnv="blue"
        else
          nextEnv="green"
        fi

        echo "🚀 Current active: ${activeEnv:-none}, Deploying to: $nextEnv"

        # Deploy new version without traffic
        echo "📦 Deploying new version to $nextEnv..."
        gcloud run deploy ${_SERVICE_NAME} \
          --image=asia.gcr.io/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA \
          --no-traffic \
          --tag=$nextEnv \
          --region=${_REGION} \
          --port=3000 \
          --memory=8Gi \
          --cpu=4 \
          --min-instances=0 \
          --max-instances=90 \
          --concurrency=90 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production" \
          --set-env-vars="NEXT_TELEMETRY_DISABLED=1" \
          --set-env-vars="NODE_OPTIONS=--expose-gc --max-old-space-size=7168 --optimize-for-size" \
          --set-env-vars="DATABASE_URL=${_DATABASE_URL}" \
          --set-env-vars="NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}" \
          --set-env-vars="REVALIDATE_SECRET_KEY=${_REVALIDATE_SECRET_KEY}" \
          --set-env-vars="NEXT_PUBLIC_DOMAIN=${_NEXT_PUBLIC_DOMAIN}" \
          --set-env-vars="CLOUDFLARE_API_TOKEN=${_CLOUDFLARE_API_TOKEN}" \
          --set-env-vars="CLOUDFLARE_ZONE_ID=${_CLOUDFLARE_ZONE_ID}" \
          --set-env-vars="YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}" \
          --set-env-vars="WORDPRESS_API_URL=${_WORDPRESS_API_URL}" \
          --set-env-vars="NEXT_PUBLIC_CMS_URL=${_NEXT_PUBLIC_CMS_URL}" \
          --set-env-vars="NEXT_PUBLIC_CDN_URL=${_NEXT_PUBLIC_CDN_URL}" \
          --set-env-vars="NEXT_PUBLIC_GCS_BUCKET=${_NEXT_PUBLIC_GCS_BUCKET}" \
          --set-env-vars="NEXT_PUBLIC_COMSCORE_ID=${_NEXT_PUBLIC_COMSCORE_ID}" \
          --set-env-vars="NEXT_PUBLIC_LOTAME_CLIENT_ID=${_NEXT_PUBLIC_LOTAME_CLIENT_ID}" \
          --set-env-vars="NEXT_PUBLIC_CB_UID=${_NEXT_PUBLIC_CB_UID}" \
          --set-env-vars="NEXT_PUBLIC_CHARTBEAT_API_KEY=${_NEXT_PUBLIC_CHARTBEAT_API_KEY}" \
          --set-env-vars="NEXT_PUBLIC_CHARTBEAT_HOST=${_NEXT_PUBLIC_CHARTBEAT_HOST}" \
          --set-env-vars="NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}" \
          --set-env-vars="NEXT_PUBLIC_WORDPRESS_SECRET=${_NEXT_PUBLIC_WORDPRESS_SECRET}" \
          --set-env-vars="NEXT_PUBLIC_WP_REFRESH_TOKEN=${_NEXT_PUBLIC_WP_REFRESH_TOKEN}" \
          --set-env-vars="GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}" \
          --set-env-vars="REVALIDATION_TOKEN=${_REVALIDATION_TOKEN}" \
          --set-env-vars="SYNC_KEY=${_SYNC_KEY}" \
          --set-env-vars="CHARTBEAT_API_KEY=${_CHARTBEAT_API_KEY}" \
          --set-env-vars="CHARTBEAT_HOST=${_CHARTBEAT_HOST}" \
          --set-env-vars="NEXT_PUBLIC_CRYPTO_IV=${_NEXT_PUBLIC_CRYPTO_IV}" \
          --set-env-vars="NEXT_PUBLIC_CRYPTO_KEY=${_NEXT_PUBLIC_CRYPTO_KEY}" \
          --set-env-vars="CONTACT_US_RECIPIENT=${_CONTACT_US_RECIPIENT}" \
          --set-env-vars="SENDGRID_API_KEY=${_SENDGRID_API_KEY}" \
          --timeout=300 \
          --service-account=${_SERVICE_ACCOUNT} \
          --quiet

        # Health check - wait for new deployment to be ready
        echo "🔍 Waiting for deployment to be ready..."
        sleep 30

        # Get the URL of the new deployment
        NEW_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.traffic[?tags='$nextEnv'].url)')

        # Switch traffic to new deployment
        echo "🔄 Switching traffic to $nextEnv..."
        gcloud run services update-traffic ${_SERVICE_NAME} \
          --to-tags=$nextEnv=100 \
          --region=${_REGION} \
          --quiet


# Substitution variables
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: fmt-v4

# Build configuration
options:
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

# Build timeout (30 minutes)
timeout: 1800s
