apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fmt-v4
  labels:
    environment: staging
    app: fmt-v4
  annotations:
    # Enable Cloud Run CPU allocation during startup
    run.googleapis.com/cpu-throttling: "false"
    # Allow CPU to be allocated even when there are no requests
    run.googleapis.com/cpu-allocation: "true"
spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Target 80% CPU utilization before scaling
        autoscaling.knative.dev/target-utilization-percentage: "80"
        # Use CPU-based autoscaling
        autoscaling.knative.dev/metric: "cpu"
        # VPC connector for private resources
        run.googleapis.com/vpc-access-connector: projects/mp-fmt-v2-stg/locations/asia-southeast1/connectors/fmt-connector
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      # Maximum concurrent requests per instance
      containerConcurrency: 10

      # Request timeout (5 minutes)
      timeoutSeconds: 60

      # Service account for the container
      serviceAccountName: fmt-v4-sa@mp-fmt-v2-stg.iam.gserviceaccount.com

      containers:
        - image: gcr.io/mp-fmt-v2-stg/fmt-v4:latest
          ports:
            - name: http1
              containerPort: 3000

          # Resource limits and requests
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi

          # Environment variables
          env:
            # Core configuration
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NODE_OPTIONS
              value: "--expose-gc --max-old-space-size=7168 --optimize-for-size"

            # Public environment variables (client-side)
            - name: NEXT_PUBLIC_DOMAIN
              value: "${NEXT_PUBLIC_DOMAIN}"
            - name: NEXT_PUBLIC_CDN_URL
              value: "${NEXT_PUBLIC_CDN_URL}"
            - name: NEXT_PUBLIC_GCS_BUCKET
              value: "${NEXT_PUBLIC_GCS_BUCKET}"
            - name: NEXT_PUBLIC_CMS_URL
              value: "${NEXT_PUBLIC_CMS_URL}"
            - name: NEXT_PUBLIC_COMSCORE_ID
              value: "${NEXT_PUBLIC_COMSCORE_ID}"
            - name: NEXT_PUBLIC_LOTAME_CLIENT_ID
              value: "${NEXT_PUBLIC_LOTAME_CLIENT_ID}"
            - name: NEXT_PUBLIC_CB_UID
              value: "${NEXT_PUBLIC_CB_UID}"
            - name: NEXT_PUBLIC_CHARTBEAT_API_KEY
              value: "${NEXT_PUBLIC_CHARTBEAT_API_KEY}"
            - name: NEXT_PUBLIC_CHARTBEAT_HOST
              value: "${NEXT_PUBLIC_CHARTBEAT_HOST}"
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              value: "${NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
            - name: NEXT_PUBLIC_CRYPTO_IV
              value: "${NEXT_PUBLIC_CRYPTO_IV}"
            - name: NEXT_PUBLIC_CRYPTO_KEY
              value: "${NEXT_PUBLIC_CRYPTO_KEY}"
            - name: NEXT_PUBLIC_WP_REFRESH_TOKEN
              value: "${NEXT_PUBLIC_WP_REFRESH_TOKEN}"
            - name: NEXT_PUBLIC_WORDPRESS_SECRET
              value: "${NEXT_PUBLIC_WORDPRESS_SECRET}"

            # Server-side environment variables
            - name: DATABASE_URL
              value: "${DATABASE_URL}"
            - name: NEXTAUTH_SECRET
              value: "${NEXTAUTH_SECRET}"
            - name: REVALIDATE_SECRET_KEY
              value: "${REVALIDATE_SECRET_KEY}"
            - name: WORDPRESS_API_URL
              value: "${WORDPRESS_API_URL}"
            - name: GOOGLE_CLIENT_SECRET
              value: "${GOOGLE_CLIENT_SECRET}"
            - name: REVALIDATION_TOKEN
              value: "${REVALIDATION_TOKEN}"
            - name: SYNC_KEY
              value: "${SYNC_KEY}"
            - name: CLOUDFLARE_API_TOKEN
              value: "${CLOUDFLARE_API_TOKEN}"
            - name: CLOUDFLARE_ZONE_ID
              value: "${CLOUDFLARE_ZONE_ID}"
            - name: CHARTBEAT_API_KEY
              value: "${CHARTBEAT_API_KEY}"
            - name: CHARTBEAT_HOST
              value: "${CHARTBEAT_HOST}"
            - name: YOUTUBE_API_KEY
              value: "${YOUTUBE_API_KEY}"
            - name: SENDGRID_API_KEY
              value: "${SENDGRID_API_KEY}"
            - name: CONTACT_US_RECIPIENT
              value: "${CONTACT_US_RECIPIENT}"

  # Traffic configuration
  traffic:
    - percent: 100
      latestRevision: true
