# Stage 1: Dependencies
FROM node:22.16-alpine AS deps

RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++ \
    linux-headers \
    build-base

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci --legacy-peer-deps --ignore-optional

# Stage 2: Builder
FROM node:22.16-alpine AS builder
WORKDIR /app

# Build-time arguments - NEXT_PUBLIC_* embedded in client bundle
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_CDN_URL
ARG NEXT_PUBLIC_GCS_BUCKET
ARG NEXT_PUBLIC_CMS_URL
ARG NEXT_PUBLIC_COMSCORE_ID
ARG NEXT_PUBLIC_LOTAME_CLIENT_ID
ARG NEXT_PUBLIC_CB_UID
ARG NEXT_PUBLIC_CHARTBEAT_API_KEY
ARG NEXT_PUBLIC_CHARTBEAT_HOST
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_CRYPTO_IV
ARG NEXT_PUBLIC_CRYPTO_KEY
ARG NEXT_PUBLIC_WP_REFRESH_TOKEN
ARG NEXT_PUBLIC_WORDPRESS_SECRET

# Server-side only build arguments
ARG DATABASE_URL
ARG WORDPRESS_API_URL
ARG REVALIDATE_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG YOUTUBE_API_KEY
ARG YOUTUBE_CHANNEL_ID
ARG YOUTUBE_WEBHOOK_URL
ARG ALLOWED_EMAIL_DOMAIN
ARG ADMIN_ALLOWED_HOST
ARG CLOUDFLARE_API_TOKEN
ARG CLOUDFLARE_ZONE_ID
ARG CHARTBEAT_API_KEY
ARG CHARTBEAT_HOST
ARG SYNC_KEY
ARG CONTACT_US_RECIPIENT
ARG SENDGRID_API_KEY
ARG ADMIN_API_KEY
ARG WEBSUB_SECRET
ARG CRON_SECRET_KEY
ARG GCS_BUCKET_NAME

# Set build environment
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Pass build args to environment for Next.js build process
ENV DATABASE_URL=${DATABASE_URL}
ENV WORDPRESS_API_URL=${WORDPRESS_API_URL}
ENV REVALIDATE_SECRET=${REVALIDATE_SECRET}
ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
ENV NEXT_PUBLIC_GCS_BUCKET=${NEXT_PUBLIC_GCS_BUCKET}
ENV NEXT_PUBLIC_CMS_URL=${NEXT_PUBLIC_CMS_URL}
ENV NEXT_PUBLIC_COMSCORE_ID=${NEXT_PUBLIC_COMSCORE_ID}
ENV NEXT_PUBLIC_LOTAME_CLIENT_ID=${NEXT_PUBLIC_LOTAME_CLIENT_ID}
ENV NEXT_PUBLIC_CB_UID=${NEXT_PUBLIC_CB_UID}
ENV NEXT_PUBLIC_CHARTBEAT_API_KEY=${NEXT_PUBLIC_CHARTBEAT_API_KEY}
ENV NEXT_PUBLIC_CHARTBEAT_HOST=${NEXT_PUBLIC_CHARTBEAT_HOST}
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
ENV NEXT_PUBLIC_CRYPTO_IV=${NEXT_PUBLIC_CRYPTO_IV}
ENV NEXT_PUBLIC_CRYPTO_KEY=${NEXT_PUBLIC_CRYPTO_KEY}
ENV NEXT_PUBLIC_WP_REFRESH_TOKEN=${NEXT_PUBLIC_WP_REFRESH_TOKEN}
ENV NEXT_PUBLIC_WORDPRESS_SECRET=${NEXT_PUBLIC_WORDPRESS_SECRET}

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/prisma ./prisma

# Copy all source files
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build Next.js application
RUN npm run build

# Stage 3: Runner
FROM node:22.16-alpine AS runner
WORKDIR /app

# Set production environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS="--expose-gc --max-old-space-size=1792 --optimize-for-size"
ENV PORT=3000

# Install runtime dependencies
RUN apk add --no-cache curl procps htop

# Runtime arguments for all environment variables
ARG DATABASE_URL
ARG WORDPRESS_API_URL
ARG REVALIDATE_SECRET
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_CDN_URL
ARG NEXT_PUBLIC_GCS_BUCKET
ARG NEXT_PUBLIC_CMS_URL
ARG NEXT_PUBLIC_COMSCORE_ID
ARG NEXT_PUBLIC_LOTAME_CLIENT_ID
ARG NEXT_PUBLIC_CB_UID
ARG NEXT_PUBLIC_CHARTBEAT_API_KEY
ARG NEXT_PUBLIC_CHARTBEAT_HOST
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_CRYPTO_IV
ARG NEXT_PUBLIC_CRYPTO_KEY
ARG NEXT_PUBLIC_WP_REFRESH_TOKEN
ARG NEXT_PUBLIC_WORDPRESS_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG SYNC_KEY
ARG CLOUDFLARE_API_TOKEN
ARG CLOUDFLARE_ZONE_ID
ARG CHARTBEAT_API_KEY
ARG CHARTBEAT_HOST
ARG YOUTUBE_API_KEY
ARG YOUTUBE_CHANNEL_ID
ARG YOUTUBE_WEBHOOK_URL
ARG SENDGRID_API_KEY
ARG CONTACT_US_RECIPIENT
ARG ADMIN_API_KEY
ARG WEBSUB_SECRET
ARG CRON_SECRET_KEY
ARG GCS_BUCKET_NAME
ARG ALLOWED_EMAIL_DOMAIN
ARG ADMIN_ALLOWED_HOST

# Set all runtime environment variables
ENV DATABASE_URL=${DATABASE_URL}
ENV WORDPRESS_API_URL=${WORDPRESS_API_URL}
ENV REVALIDATE_SECRET=${REVALIDATE_SECRET}
ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
ENV NEXT_PUBLIC_GCS_BUCKET=${NEXT_PUBLIC_GCS_BUCKET}
ENV NEXT_PUBLIC_CMS_URL=${NEXT_PUBLIC_CMS_URL}
ENV NEXT_PUBLIC_COMSCORE_ID=${NEXT_PUBLIC_COMSCORE_ID}
ENV NEXT_PUBLIC_LOTAME_CLIENT_ID=${NEXT_PUBLIC_LOTAME_CLIENT_ID}
ENV NEXT_PUBLIC_CB_UID=${NEXT_PUBLIC_CB_UID}
ENV NEXT_PUBLIC_CHARTBEAT_API_KEY=${NEXT_PUBLIC_CHARTBEAT_API_KEY}
ENV NEXT_PUBLIC_CHARTBEAT_HOST=${NEXT_PUBLIC_CHARTBEAT_HOST}
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
ENV NEXT_PUBLIC_CRYPTO_IV=${NEXT_PUBLIC_CRYPTO_IV}
ENV NEXT_PUBLIC_CRYPTO_KEY=${NEXT_PUBLIC_CRYPTO_KEY}
ENV NEXT_PUBLIC_WP_REFRESH_TOKEN=${NEXT_PUBLIC_WP_REFRESH_TOKEN}
ENV NEXT_PUBLIC_WORDPRESS_SECRET=${NEXT_PUBLIC_WORDPRESS_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV SYNC_KEY=${SYNC_KEY}
ENV CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
ENV CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
ENV CHARTBEAT_API_KEY=${CHARTBEAT_API_KEY}
ENV CHARTBEAT_HOST=${CHARTBEAT_HOST}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
ENV YOUTUBE_WEBHOOK_URL=${YOUTUBE_WEBHOOK_URL}
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV CONTACT_US_RECIPIENT=${CONTACT_US_RECIPIENT}
ENV ADMIN_API_KEY=${ADMIN_API_KEY}
ENV WEBSUB_SECRET=${WEBSUB_SECRET}
ENV CRON_SECRET_KEY=${CRON_SECRET_KEY}
ENV GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
ENV ALLOWED_EMAIL_DOMAIN=${ALLOWED_EMAIL_DOMAIN}
ENV ADMIN_ALLOWED_HOST=${ADMIN_ALLOWED_HOST}

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Create required directories
RUN mkdir -p .next/cache && chown -R nextjs:nodejs .next

# Copy only necessary files from builder
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone/ ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/prisma ./prisma

# Switch to non-root user
USER nextjs

EXPOSE 3000

CMD ["node", "--expose-gc", "server.js"]
