services:
  app:
    environment:
      - TZ=Asia/Kuala_Lumpur
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time arguments (public variables)
        - NEXT_PUBLIC_COMSCORE_ID=${NEXT_PUBLIC_COMSCORE_ID}
        - NEXT_PUBLIC_LOTAME_CLIENT_ID=${NEXT_PUBLIC_LOTAME_CLIENT_ID}
        - NEXT_PUBLIC_CB_UID=${NEXT_PUBLIC_CB_UID}
        - NEXT_PUBLIC_CHARTBEAT_API_KEY=${NEXT_PUBLIC_CHARTBEAT_API_KEY}
        - NEXT_PUBLIC_CHARTBEAT_HOST=${NEXT_PUBLIC_CHARTBEAT_HOST}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
        - NEXT_PUBLIC_GCS_BUCKET=${NEXT_PUBLIC_GCS_BUCKET}
        # Runtime arguments (private variables)
        - WORDPRESS_API_URL=${WORDPRESS_API_URL}
        - WORDPRESS_AUTH_REFRESH_TOKEN=${WORDPRESS_AUTH_REFRESH_TOKEN}
        - WORDPRESS_PREVIEW_SECRET=${WORDPRESS_PREVIEW_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - REVALIDATION_TOKEN=${REVALIDATION_TOKEN}
        - SYNC_KEY=${SYNC_KEY}
        - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
        - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
        - CHARTBEAT_API_KEY=${CHARTBEAT_API_KEY}
        - CHARTBEAT_HOST=${CHARTBEAT_HOST}
        - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    ports:
      - '3000:3000'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G