import siteConfig from "../site-config";

export const OrgJsonLD = {
  "@context": "https://www.schema.org",
  "@type": "NewsMediaOrganization",
  additionalType: "Organization",
  name: `${siteConfig.siteName}`,
  legalName: "FMT Media Sdn Bhd",
  slogan: `${siteConfig.tagline}`,
  url: `${siteConfig.baseUrl}`,
  foundingDate: "2009-11-01",
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    telephone: "+60378872888",
  },
  email: "mailto:admin@freemalaysiatoday.com",
  knowsLanguage: ["Malay", "English"],
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: 4.4,
    ratingCount: 2608867,
  },
  numberOfEmployees: {
    "@type": "QuantitativeValue",
    minValue: 100,
    maxValue: 500,
  },
  mainEntityOfPage: {
    "@type": "WebSite",
    "@id": "https://www.freemalaysiatoday.com/",
    url: "https://www.freemalaysiatoday.com/",
  },
  isAccessibleForFree: true,
  sameAs: [
    "https://www.facebook.com/freemalaysiatoday/",
    "https://www.instagram.com/freemalaysiatoday",
    "https://x.com/fmtoday",
    "https://t.me/FreeMalaysiaToday",
    "https://www.youtube.com/@FreeMalaysiaToday",
    "https://www.linkedin.com/company/fmt-news/",
    "https://www.tiktok.com/@freemalaysiatoday",
    "https://en.wikipedia.org/wiki/Free_Malaysia_Today",
    "https://ms.wikipedia.org/wiki/Free_Malaysia_Today",
  ],
  logo: {
    "@context": "https://schema.org",
    "@type": "ImageObject",
    url: siteConfig.iconPath,
    contentUrl: siteConfig.iconPath,
    width: 512,
    height: 512,
    creditText: "Free Malaysia Today",
    license: `${siteConfig.baseUrl}/privacy-policy/`,
    acquireLicensePage: `${siteConfig.baseUrl}/privacy-policy/`,
    creator: {
      "@type": "Organization",
      name: "Free Malaysia Today",
      url: `${siteConfig.baseUrl}`,
    },
    copyrightNotice: `© ${siteConfig.siteName}, ${new Date().getFullYear()}`,
  },
  description: `${siteConfig.siteDescription}`,
  location: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      streetAddress:
        "The West Wing, Menara Axis, Ground Floor, Quattro West, 4, Persiaran Barat",
      addressLocality: "Petaling Jaya",
      addressRegion: "Selangor",
      postalCode: "46200",
      addressCountry: "MY",
    },
    name: "FMT Media Sdn Bhd",
    sameAs: `${siteConfig.baseUrl}`,
    geo: {
      "@type": "GeoCoordinates",
      latitude: "3.1037209336764953",
      longitude: "101.64165328465576",
    },
  },
  alternateName: [
    "FMT",
    "FreeMalaysiaToday",
    "Free Malaysia Today",
    "fmtoday",
    "FMT News",
    "FMTNews",
    "FMT Media Sdn Bhd",
    "FMT Media",
  ].join(", "),
  keywords: [
    "Free Malaysia Today",
    "Malaysia News",
    "Latest Malaysia News",
    "Breaking News Malaysia",
    "Malaysia Politics News",
    "Malaysia Economic News",
    "Malaysia International News",
    "Free News Malaysia",
    "24/7 News Malaysia",
    "Malaysian Cultural News",
    "English Malay News Online",
    "Comprehensive Malaysian News.",
  ].join(", "),
};

export const websiteJSONLD = {
  "@context": "https://schema.org",
  "@type": ["WebSite", "CreativeWork"],
  name: "Free Malaysia Today Website",
  description:
    "Explore 24/7 news on politics, economy, and more with Free Malaysia Today. Your source for unbiased Malaysian news in English & Malay since 2009.",
  url: `${siteConfig.baseUrl}`,
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${siteConfig.baseUrl}search/?term={search_term_string}&category=all`,
    },
    "query-input": "required name=search_term_string",
  },
};

export const WebPageJsonLD = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  additionalType: "News_Website",
  url: `${siteConfig.baseUrl}`,
  name: `${siteConfig.baseUrl}`,
  inLanguage: [
    "en-MY",
    "en-US",
    "en-GB",
    "en-AU",
    "en-CA",
    "en-NZ",
    "en-IE",
    "en-IN",
    "en-SG",
    "en-ZA",
    "en-PH",
    "en-HK",
    "en-PK",
    "ms-MY",
    "id-ID",
    "jv-ID",
    "su-ID",
    "ms-BN",
    "ms-SG",
  ],
  publisher: OrgJsonLD,
  isPartOf: websiteJSONLD,
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        item: {
          "@id": "https://www.freemalaysiatoday.com/",
          name: "Home",
        },
      },
    ],
  },
};

export const socialChannelsJsonLD = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Official Channels - Free Malaysia Today",
  url: "https://www.freemalaysiatoday.com/channels",
  description:
    "Explore the official social media channels of Free Malaysia Today including Facebook, Instagram, YouTube, WhatsApp, Telegram, and more.",
  publisher: {
    "@type": "Organization",
    name: "Free Malaysia Today",
    url: "https://www.freemalaysiatoday.com",
    logo: {
      "@type": "ImageObject",
      url: "https://media.freemalaysiatoday.com/wp-content/uploads/2018/09/logo-white-fmt-800x500.jpg",
    },
    sameAs: [
      "https://www.facebook.com/freemalaysiatoday/",
      "https://www.instagram.com/freemalaysiatoday",
      "https://x.com/fmtoday",
      "https://www.youtube.com/user/FreeMalaysiaToday",
      "https://www.whatsapp.com/channel/0029Va78sJa96H4VaQu6580F",
      "https://en.wikipedia.org/wiki/Free_Malaysia_Today",
      "https://t.me/FreeMalaysiaToday",
      "https://www.linkedin.com/company/fmt-news/",
      "https://www.tiktok.com/@freemalaysiatoday?_t=8UsJzt8DCWP&_r=1",
      "https://news.google.com/publications/CAAqBwgKMJ6DqAwwsIu2BA?hl=en-MY&gl=MY&ceid=MY%3Aen",
    ],
  },
};
