interface TargetingParamsProps {
  section: string[];
}

export const generalTargetingParams = ({ section }: TargetingParamsProps) => ({
  pos: "listing",
  section: section || ["category-landing-page", "landing-page"],
  key: [
    "Free Malaysia Today",
    "Malaysia News",
    "Latest Malaysia News",
    "Breaking News Malaysia",
    "Malaysia Politics News",
    "gambling",
    "religion",
    "alcohol",
    "lgbt",
    "sex",
    "drug abuse",
    "get rich",
    "match-making",
    "dating",
    "lottery",

    // News keywords
    "breaking-news",
    "current-affairs",
    "politics",
    "government",
    "parliament",
    "crime",
    "court",
    "police",
    "investigation",
    "accident",
    "disaster",
    "education",
    "school",
    "university",
    "environment",
    "climate",

    // Malaysia specific
    "malaysian-news",
    "local-news",
    "national-news",
    "state-news",
    "pribumi",
    "bumiputera",
    "malay",
    "chinese",
    "indian",
    "community",

    // Borneo specific
    "sabah",
    "sarawak",
    "borneo",
    "east-malaysia",
    "dayak",
    "kadazan",
    "dusun",
    "iban",
    "native",
    "indigenous",

    // Berita keywords
    "berita-semasa",
    "berita-terkini",
    "isu-semasa",
    "komuniti",
    "tempatan",
    "nasional",
    "parlimen",
    "kerajaan",
    "mahkamah",
    "pendidikan",
    "kesihatan",
    "alam-sekitar",
    "politik",

    // Business keywords
    "economy",
    "finance",
    "market",
    "stocks",
    "shares",
    "trading",
    "investment",
    "banking",
    "currency",
    "forex",
    "commodities",
    "property",
    "real-estate",
    "oil-and-gas",
    "technology",
    "startup",
    "sme",
    "enterprise",
    "corporate",
    "industry",

    // Lifestyle keywords
    "lifestyle",
    "living",
    "culture",
    "trends",
    "fashion",
    "food",
    "cuisine",
    "restaurant",
    "recipes",
    "cooking",
    "health",
    "wellness",
    "fitness",
    "medical",
    "healthcare",
    "family",
    "parenting",
    "children",
    "marriage",
    "relationships",
    "entertainment",
    "celebrities",
    "movies",
    "music",
    "arts",
    "travel",
    "tourism",
    "vacation",
    "hotel",
    "destination",
    "technology",
    "gadgets",
    "devices",
    "apps",
    "software",
    "pets",
    "animals",
    "veterinary",
    "pet-care",

    // Sports keywords
    "sports-news",
    "athletics",
    "tournament",
    "championship",
    "football",
    "soccer",
    "premier-league",
    "fifa",
    "uefa",
    "badminton",
    "bam",
    "thomas-cup",
    "uber-cup",
    "motorsports",
    "f1",
    "racing",
    "motogp",
    "superbikes",
    "tennis",
    "grand-slam",
    "atp",
    "wta",
    "olympics",
    "sea-games",
    "asian-games",

    // Opinion keywords
    "editorial",
    "opinion",
    "commentary",
    "analysis",
    "perspective",
    "column",
    "columnist",
    "viewpoint",
    "expert",
    "insight",
    "letters",
    "feedback",
    "public-opinion",
    "reader-views",

    // World news keywords
    "international",
    "global",
    "world-news",
    "foreign-affairs",
    "asia",
    "europe",
    "america",
    "middle-east",
    "africa",
    "united-nations",
    "diplomacy",
    "trade",
    "conflict",

    // Southeast Asia specific
    "asean",
    "southeast-asia",
    "indonesia",
    "thailand",
    "singapore",
    "philippines",
    "vietnam",
    "myanmar",
    "cambodia",
    "laos",
    "brunei",
    "timor-leste",

    // Restricted/Sensitive topics
    "gambling",
    "religion",
    "alcohol",
    "lgbt",
    "sex",
    "drug-abuse",
    "get-rich",
    "match-making",
    "dating",
    "lottery",
    "adult-content",
    "sensitive-content",
    "mature-themes",

    // General content types
    "feature",
    "exclusive",
    "special-report",
    "interview",
    "investigation",
    "live-updates",
    "breaking",
    "alert",
    "premium-content",
    "subscription",
    "paywall",
  ],
});

export const gerneralTargetingKeys = [
  "Free Malaysia Today",
  "Malaysia News",
  "Latest Malaysia News",
  "Breaking News Malaysia",
  "Malaysia Politics News",
  "gambling",
  "religion",
  "alcohol",
  "lgbt",
  "sex",
  "drug abuse",
  "get rich",
  "match-making",
  "dating",
  "lottery",
];
