export const sportsLandingTargetingParams = {
    pos: "listing",
    section: [
      "sports",
      "landing-page",
      "sports-landing-page",
      "football",
      "badminton",
      "motorsport",
      "tennis",
    ],
    key: [
      // Football
      "football-news",
      "malaysian-football",
      "premier-league",
      "la-liga",
      "bundesliga",
      "serie-a",
      "ligue-1",
      "champions-league",
      "europa-league",
      "malaysia-super-league",
      "afc-champions-league",
      "world-cup",
      "euro-championship",
      "copa-america",
      "asian-cup",
      "football-transfers",
      "harimau-malaya",
  
      // Badminton
      "badminton-news",
      "malaysian-badminton",
      "lee-zii-jia",
      "bwf-world-tour",
      "thomas-cup",
      "uber-cup",
      "sudirman-cup",
      "all-england",
      "malaysia-open",
      "indonesia-open",
      "asian-games-badminton",
      "olympics-badminton",
      "badminton-rankings",
  
      // Motorsport
      "motorsport-news",
      "formula-1",
      "motogp",
      "malaysian-gp",
      "singapore-gp",
      "f1-drivers",
      "f1-teams",
      "f1-standings",
      "lewis-hamilton",
      "max-verstappen",
      "ferrari",
      "mercedes",
      "red-bull-racing",
      "sepang-circuit",
      "rally",
      "superbikes",
  
      // Tennis
      "tennis-news",
      "grand-slams",
      "australian-open",
      "french-open",
      "wimbledon",
      "us-open",
      "atp-tour",
      "wta-tour",
      "tennis-rankings",
      "davis-cup",
      "fed-cup",
  
      // Other Sports Categories
      "olympics",
      "sea-games",
      "asian-games",
      "commonwealth-games",
      "athletics",
      "swimming",
      "cycling",
      "boxing",
      "cricket",
      "golf",
      "rugby",
      "volleyball",
      "hockey",
      "table-tennis",
      "esports",
  
      // Sports Topics
      "malaysian-athletes",
      "sports-analysis",
      "match-reports",
      "live-scores",
      "tournament-schedules",
      "sports-injuries",
      "team-standings",
      "player-transfers",
      "sports-technology",
      "sports-business",
      "sports-facilities",
      "youth-development",
      "sports-ministry",
      "national-sports-council",
      "sports-associations",
    ],
  
    // Additional targeting options
    contentType: "sports",
    pageType: "category",
    region: ["malaysia", "southeast-asia", "asia", "europe", "international"],
    language: "english",
  
    // Sports specific parameters
    competitionLevel: ["international", "national", "club", "youth", "amateur"],
    eventType: [
      "tournament",
      "league",
      "championship",
      "friendly",
      "qualification",
    ],
    coverage: [
      "live-updates",
      "match-report",
      "analysis",
      "interview",
      "feature",
      "preview",
      "review",
    ],
  };
  
  // Sports Subcategory-specific targeting params
  export const footballTargetingParams = {
    ...sportsLandingTargetingParams,
    section: ["sports", "football"],
    key: [
      "football-news",
      "malaysian-football",
      "premier-league",
      "la-liga",
      "bundesliga",
      "serie-a",
      "ligue-1",
      "champions-league",
      "europa-league",
      "malaysia-super-league",
      "afc-champions-league",
      "world-cup",
      "euro-championship",
      "copa-america",
      "asian-cup",
      "football-transfers",
      "harimau-malaya",
    ],
  };
  
  export const badmintonTargetingParams = {
    ...sportsLandingTargetingParams,
    section: ["sports", "badminton"],
    key: [
      "badminton-news",
      "malaysian-badminton",
      "lee-zii-jia",
      "bwf-world-tour",
      "thomas-cup",
      "uber-cup",
      "sudirman-cup",
      "all-england",
      "malaysia-open",
      "indonesia-open",
      "asian-games-badminton",
      "olympics-badminton",
      "badminton-rankings",
    ],
  };
  
  export const motorsportTargetingParams = {
    ...sportsLandingTargetingParams,
    section: ["sports", "motorsport"],
    key: [
      "motorsport-news",
      "formula-1",
      "motogp",
      "malaysian-gp",
      "singapore-gp",
      "f1-drivers",
      "f1-teams",
      "f1-standings",
      "lewis-hamilton",
      "max-verstappen",
      "ferrari",
      "mercedes",
      "red-bull-racing",
      "sepang-circuit",
      "rally",
      "superbikes",
    ],
  };
  
  export const tennisTargetingParams = {
    ...sportsLandingTargetingParams,
    section: ["sports", "tennis"],
    key: [
      "tennis-news",
      "grand-slams",
      "australian-open",
      "french-open",
      "wimbledon",
      "us-open",
      "atp-tour",
      "wta-tour",
      "tennis-rankings",
      "davis-cup",
      "fed-cup",
    ],
  };
  